### ISSUE TITLE
the logic is wrong

### ISSUE THREAD

**Issue by nationalflag** [Randl/DropBlock-pytorch#1]
https://github.com/Randl/DropBlock-pytorch/blob/421222d494b2788ca53d13ec8e30dd3f4b5d6a3f/DropBlock.py#L42

**Comment by Randl** [comment]
why? 
If the point (x,y) is in block around chosen (xp, yp), then the opposite is true. Thus we just sum block around each point

**Comment by nationalflag** [comment]
The logic in the paper is "if the chosen (xp, yp) is zero, set all points in block around (xp, yp) to be zero"
The logic of your implementation seems to be "if all points in block around the chosen (xp, yp) are zero, set the point (xp, yp) to be zero"

**Comment by Randl** [comment]
I believe you misread the code. Take a look at line https://github.com/Randl/DropBlock-pytorch/blob/421222d494b2788ca53d13ec8e30dd3f4b5d6a3f/DropBlock.py#L48

The logic is "if neither point in block around (x,y) is chosen, keep (x,y)", which is equivalent to the logic of the paper. You can take a look on resulting mask to confirm it

**Comment by nationalflag** [comment]
It should be "if neither point in 2*block_size-1 around (x,y) is chosen, keep (x,y)", because (x,y) can be the top_left of a block, also can be the bottom_right of another block.

**Comment by Randl** [comment]
If it is top left of block, then it's coordinates are (xp-bs//2,yp-bs//2), where bs is block size. that means +- bs//2 is enough to catch all possible block centers

**Comment by nationalflag** [comment]
For this picture, block size is 3, the black dot is (xp, yp), whether we keep the (xp, yp) or not is actually depend on the red block

![112133830](https://user-images.githubusercontent.com/15048847/47989571-50775100-e120-11e8-8c6e-678d67ebd0b1.jpg)

**Comment by nationalflag** [comment]
Sorry. You are right. I'm  wrong.

**Comment by Randl** [comment]
right, thus we drop centers of both blue squares (those would be exactly convolution filters)

**Comment by liuyuancv** [comment]
In my opinion, when the block_size in the code is set to 7, the real block size described in the original paper is 13. Is it right?
